[project]
name = "tokamax"
authors = [{ name = "Sebastian Bodenstein", email = "sbodenstein@google.com" }, {name = "Chris Jones", email = "cjfj@google.com" }]
maintainers = [{ name = "Stanley Tzeng", email = "stzeng@google.com" }, {name = " Ani Udipi", email = "udipi@google.com" }]
description = "A Pallas Custom Kernel Library."
readme = "README.md"
dynamic = ["version"]
license = { file = "LICENSE" }
requires-python = ">=3.11"
dependencies = [
"absl-py>=2.3.0",
"jax[cuda12, tpu]",
"jaxlib",
"chex>=0.1.81",
"triton>=3.0.0",
"nvidia-cudnn-cu12>=9.0.0",
"jax-triton",
"jaxtyping>=0.3",
"typeguard==2.13.3",
"google-benchmark>=1.9.0",
"pydantic>=2.11.0",
"torch_xla[pallas]",
"xprof", 
"pytest",]
